### Numpy -> Numerical Python is a library -> core library of python
### pip install numpy

In [1]:
import numpy as np

In [9]:
# Create a 1D array
arr1 = np.array([1,2,3])
arr1
# (type(arr1))
# (len(arr1))
# (arr1[1])
# (arr1[0:])

array([1, 2, 3])

In [20]:
#functions
(np.zeros(6))  #zeros array
# (np.ones(5))   #ones array
# (np.empty(4))  #empty array              #every time comes a differnt value why?
# (np.arange(10))  #range
# (np.arange(2,20))  #specific range
# (np.arange(2,20,3))  #specific range withy specific interval
# #table of 9
# (np.arange(9,99,9))
# (np.linspace(0,20, num=5))   #specific line space/specific interval
# (np.ones(20, dtype=np.int64)) #specify datatype

array([0., 0., 0., 0., 0., 0.])

In [25]:
#Array Functions
arr2 = np.array([10,65,8.5,89,24,75,43,76,1.2,0.6,79])
arr2
# arr2.sort()   #sort
# arr2
# np.concatenate((arr1, arr2)) #concatenate

array([10. , 65. ,  8.5, 89. , 24. , 75. , 43. , 76. ,  1.2,  0.6, 79. ])

In [31]:
#Create a 2D array
arr3 = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr3
# arr4 = np.array([[6,7,8,9,10],[10,9,8,7,6]])
# arr4
# np.concatenate((arr3, arr4)) #concatenate
# np.concatenate((arr3, arr4), axis=0) #concatenate  y axis
# np.concatenate((arr3, arr4), axis=1) #concatenate  x axis

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [36]:
#Create a 3D array
arr5 = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
arr5
# arr5.ndim  #to find the number of dimensions
# arr5.size  # to find num of elements
# arr5.shape  # to find shape (dims,rows,cols)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [38]:
# Reshape arrays 
arr6= np.array([1,2,3,4,5,6,7,8,9])
arr6.reshape(3,3) #3*3=9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# Convert 1D array into 2D array - row wise
arr7 = np.array([1,2,3,4,5,6,7,8,9])
arr7.shape
# arr8= arr7[np.newaxis, :]
# arr8.shape

(1, 9)

In [45]:
# Convert 1D array into 2D array - coloumn wise
arr9= np.array([1,2,3,4,5,6,7,8,9])
arr9.shape
arr10= arr9[:, np.newaxis]
arr10.shape

(9, 1)

In [50]:
# array
a= np.array([1,2,3,4,5])
a
# a*3
# a+3
# a.mean()  #array mean
# a.sum()  #array sum

np.int64(15)